services:
  - type: web
    name: autoscale-notifier
    env: docker
    plan: free
    repo: https://github.com/turkia1bdullah/render-autoscale-notifier
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - autoscale-watcher.sh
        - Dockerfile
        - render.yaml
    envVars:
      - key: RENDER_API_KEY
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: SERVICE_ID_APP
        sync: false
      - key: SERVICE_ID_DASHBOARD
        sync: false
    ports:
      - port: 10001  # Required dummy port for web services
